TR_TEAMS = {
    "MEXICO": "Meksika", "SOUTH AFRICA": "Güney Afrika", "SOUTH KOREA": "Güney Kore", 
    "KOREA REPUBLIC": "Güney Kore", "REP. KOREA": "Güney Kore", "CANADA": "Kanada", 
    "USA": "ABD", "UNITED STATES": "ABD", "TURKEY": "Türkiye", "TÜRKIYE": "Türkiye", 
    "GERMANY": "Almanya", "NETHERLANDS": "Hollanda", "JAPAN": "Japonya", 
    "BELGIUM": "Belçika", "SPAIN": "İspanya", "FRANCE": "Fransa", "ARGENTINA": "Arjantin", 
    "PORTUGAL": "Portekiz", "ENGLAND": "İngiltere", "CROATIA": "Hırvatistan", 
    "BRAZIL": "Brezilya", "MOROCCO": "Fas", "ECUADOR": "Ekvador", "TUNISIA": "Tunus", 
    "IRAN": "İran", "IR IRAN": "İran", "GHANA": "Gana", "PANAMA": "Panama", 
    "URUGUAY": "Uruguay", "COLOMBIA": "Kolombiya", "SWITZERLAND": "İsviçre", 
    "DENMARK": "Danimarka", "SERBIA": "Sırbistan", "POLAND": "Polonya", 
    "AUSTRALIA": "Avustralya", "SAUDI ARABIA": "Suudi Arabistan", "CZECHIA": "Çekya", 
    "CZECH REPUBLIC": "Çekya", "BOSNIA AND HERZEGOVINA": "Bosna-Hersek", 
    "BOSNIA-HERZEGOVINA": "Bosna-Hersek", "QATAR": "Katar", "SCOTLAND": "İskoçya", 
    "IVORY COAST": "Fildişi Sahili", "CÔTE D'IVOIRE": "Fildişi Sahili", 
    "COTE D'IVOIRE": "Fildişi Sahili", "SWEDEN": "İsveç", "EGYPT": "Mısır", 
    "NEW ZEALAND": "Yeni Zelanda", "CAPE VERDE": "Yeşil Burun Adaları", 
    "CABO VERDE": "Yeşil Burun Adaları", "CAPE VERDE ISLANDS": "Yeşil Burun Adaları", 
    "IRAQ": "Irak", "NORWAY": "Norveç", "AUSTRIA": "Avusturya", "ALGERIA": "Cezayir", 
    "JORDAN": "Ürdün", "DR CONGO": "Demokratik Kongo Cumhuriyeti", 
    "CONGO DR": "Demokratik Kongo Cumhuriyeti", "DEMOCRATIC REPUBLIC OF THE CONGO": "Demokratik Kongo Cumhuriyeti", 
    "UZBEKISTAN": "Özbekistan"
}
