name: Puan Durumu Guncelle
on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch:    # Manuel çalıştırmayı sağlar (test için çok önemli)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Git'e dosya yazabilmesi için bu yetki şart
    steps:
      - uses: actions/checkout@v3
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Gerekli Paketleri Yukle
        run: pip install requests
      - name: Kodu Calistir
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python update_live_data.py
      - name: Degisiklikleri Kaydet ve Push Et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "index.html guncellendi" && git push)
